apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "GuideLLM used to benchmark LLM inference"
    openshift.io/display-name: Demo - guideLLM
  # labels:
  #   openshift.io/cluster-monitoring: "true"
  name: demo-guidellm
