apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guidellm-data
  namespace: demo-guidellm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
