apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen-pd
spec:
  # Main/decode pool replica count
  replicas: 1
  model:
    uri: hf://Qwen/Qwen3-0.6B
    name: Qwen/Qwen3-0.6B
  router:
    scheduler:
      template:
        containers:
          - name: main
            args:
              - -v=4 # Debug level
              - --poolName
              - "{{ ChildName .ObjectMeta.Name `-inference-pool` }}"
              - --poolNamespace
              - "{{ .ObjectMeta.Namespace }}"
              - --zap-encoder
              - json
              - --grpcPort
              - "9002"
              - --grpcHealthPort
              - "9003"
              - --secureServing
              - --modelServerMetricsScheme
              - https
              - --modelServerMetricsHttpsInsecureSkipVerify
              - --certPath
              - /etc/ssl/certs
              - --configText
              - |2

                apiVersion: inference.networking.x-k8s.io/v1alpha1
                kind: EndpointPickerConfig
                plugins:
                - type: pd-profile-handler
                  parameters:
                    threshold: 30000
                - type: prefill-header-handler
                - type: prefill-filter
                - type: decode-filter
                - type: random-picker
                  parameters:
                    maxNumOfEndpoints: 1
                schedulingProfiles:
                - name: prefill
                  plugins:
                  - pluginRef: prefill-filter
                  - pluginRef: random-picker
                - name: decode
                  plugins:
                  - pluginRef: decode-filter
                  - pluginRef: random-picker
    route: { }
    gateway: { }
  template:
    containers:
      - name: main
        env:
          # Pod IP for KV transfer side channel
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: VLLM_NIXL_ABORT_REQUEST_TIMEOUT
            value: "100000"
          # Enable KV cache transfer via NixlConnector (RDMA-based)
          - name: VLLM_ADDITIONAL_ARGS
            value: "--kv-transfer-config '{\"kv_connector\":\"NixlConnector\",\"kv_role\":\"kv_both\"}' --disable-uvicorn-access-log --block-size 128"
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: '4'
            memory: 8Gi
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 5
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
  prefill:
    # Prefill pool replica count (higher for concurrent prefill requests)
    replicas: 1
    template:
      containers:
        - name: main
          env:
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VLLM_ADDITIONAL_ARGS
              value: "--kv-transfer-config '{\"kv_connector\":\"NixlConnector\",\"kv_role\":\"kv_both\"}' --disable-uvicorn-access-log --block-size 128"
            - name: VLLM_NIXL_ABORT_REQUEST_TIMEOUT
              value: "100000"
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: '4'
              memory: 8Gi
              nvidia.com/gpu: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTPS
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
