apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: gpt-oss-20b
  namespace: demo-llm
spec:
  replicas: 1
  model:
    # uri: pvc://<name-of-pvc>/<optional-subfolder>
    uri: <patch-me>
    name: openai/gpt-oss-20b
  router:
    gateway: {}
    route: {}
    scheduler: {}
  template:
    containers:
      - name: main
        env:
          # disable uvicorn access log to reduce log noise
          - name: VLLM_ADDITIONAL_ARGS
            value: "--disable-uvicorn-access-log"
        resources:
          limits:
            cpu: '4'
            memory: 16Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '1'
            memory: 8Gi
            nvidia.com/gpu: '1'
        livenessProbe:
          initialDelaySeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 60
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
