apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: gpt-oss-20b-pfd
  namespace: demo-llm
spec:
  replicas: 1
  model:
    uri: <patch-me>
    name: openai/gpt-oss-20b
  router:
    scheduler:
      template:
        containers:
          - name: main
            args:
              - -v=4 # Debug level
              - --poolName
              - "{{ ChildName .ObjectMeta.Name `-inference-pool` }}"
              - --poolNamespace
              - "{{ .ObjectMeta.Namespace }}"
              - --zap-encoder
              - json
              - --grpcPort
              - "9002"
              - --grpcHealthPort
              - "9003"
              - --secureServing
              - --modelServerMetricsScheme
              - https
              - --modelServerMetricsHttpsInsecureSkipVerify
              - --certPath
              - /etc/ssl/certs
              - --configText
              - |2

                apiVersion: inference.networking.x-k8s.io/v1alpha1
                kind: EndpointPickerConfig
                plugins:
                - type: pd-profile-handler
                  parameters:
                    threshold: 30000
                - type: prefill-header-handler
                - type: prefill-filter
                - type: decode-filter
                - type: random-picker
                  parameters:
                    maxNumOfEndpoints: 1
                schedulingProfiles:
                - name: prefill
                  plugins:
                  - pluginRef: prefill-filter
                  - pluginRef: random-picker
                - name: decode
                  plugins:
                  - pluginRef: decode-filter
                  - pluginRef: random-picker
    gateway: {}
    route: {}
  template:
    containers:
      - name: main
        env:
          # disable uvicorn access log to reduce log noise
          # Enable KV cache transfer via NixlConnector (RDMA-based)
          - name: VLLM_ADDITIONAL_ARGS
            value: "--disable-uvicorn-access-log --kv-transfer-config '{\"kv_connector\":\"NixlConnector\",\"kv_role\":\"kv_both\"}' --block-size 128"
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: VLLM_LOGGING_LEVEL
            value: "DEBUG"
          - name: VLLM_NIXL_ABORT_REQUEST_TIMEOUT
            value: "100000"
        resources:
          limits:
            cpu: '4'
            memory: 16Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '1'
            memory: 8Gi
            nvidia.com/gpu: '1'
        livenessProbe:
          initialDelaySeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: 8001
            scheme: HTTPS
          failureThreshold: 60
          periodSeconds: 10
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
  prefill:
    replicas: 1
    template:
      containers:
        - name: main
          env:
            # disable uvicorn access log to reduce log noise
            # Enable KV cache transfer via NixlConnector (RDMA-based)
            - name: VLLM_ADDITIONAL_ARGS
              value: "--disable-uvicorn-access-log --kv-transfer-config '{\"kv_connector\":\"NixlConnector\",\"kv_role\":\"kv_both\"}' --block-size 128"
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VLLM_LOGGING_LEVEL
              value: "DEBUG"
            - name: VLLM_NIXL_ABORT_REQUEST_TIMEOUT
              value: "100000"
          resources:
            limits:
              cpu: '4'
              memory: 16Gi
              nvidia.com/gpu: '1'
            requests:
              cpu: '1'
              memory: 8Gi
              nvidia.com/gpu: '1'
          livenessProbe:
            initialDelaySeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTPS
            failureThreshold: 60
            periodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
